language: bash
services: docker
sudo: required

notifications:
  slack:
    secure: lEIsp75/vM5j2dJvMfT8HFVEEWHn7gPYJOiX6Sx1tU+u6tC6RMGn46cLGau0bcFsrv3FIREKqLuw2fmrwKn2+iOSAVlyoEQBY2o713tOmc/nvqpPyCcJ29383V7GLRSiUyJCv+0rY6szA661g7oPVJQiNBh1LwTSXnJG2OEK+3OlZ061Oq6gArYaujr+payr4izC8RheBYXDE1oBd6S2JZVQRjSngTkv81SbTZJ0/C1Cb8TVQuuUAW3YTJr+0dQwqK75pB4a8jeA+WeRXNyK2OoyL7DnMtbxPl+3okGl5Qa2JIOzQIe4aLIIWbpQ9crb5P3Jp1e3OdLAU6VJZI4nHQp8Lnjgv8LJqZaZb2M9FAGwfyN0iOkHFN12Bt9dPbvPqF9lYhKZ1EZYIElPf2ypwqhHwFKrjUcurWURKbwPcIQmPPzE5dBJ7c6blyvvX+65hucoF274zl2LVcp+abutqG80jaQGqdZZWX/fgi+qW73nNkh6bdWq2OcLB4kTJPzpvOiIQe+rkXgxg5ve3fsjmAZpjZ9naYde1EAuJPLZ4p0o9/BFMcOzRcwig2Sl6ZAJY3jOXFo2hHlOWDlMKKqew+xOhDW2Llc8cZ+SnKvLA+MjshaEB8dtHcDDVo+9fyPj3JQkyRMtI0ZNen9/6Kmeai5ah8xEL7qvSAwIrkNILEg=
    on_success: change

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -t napnap75/rpi-gandi:latest .
  - docker images
#  - docker run --rm -e GANDI_API_KEY="$GANDI_API_KEY" -e GANDI_DOMAIN="$GANDI_DOMAIN" -e GANDI_HOST="$GANDI_HOST" napnap75/rpi-gandi:latest
  
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push napnap75/rpi-gandi:latest
  - export CURRENTDATE=$(date +%y%m%d)
  - docker tag napnap75/rpi-gandi:latest napnap75/rpi-gandi:$CURRENTDATE
  - docker push napnap75/rpi-gandi:$CURRENTDATE
  
